version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  video-process:
    lang: python3-http-debian
    handler: ./video-process
    image: imsuraj/video-process:latest

