version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  python-bfs:
    lang: python3-http
    handler: ./graph-bfs
    image: imsuraj/graph-bfs:latest
    labels:
      com.openfaas.scale.min: "2"
      com.openfaas.scale.max: "5"

