version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  nodejs-dynamic-html:
    lang: node20
    handler: ./nodejs-dynamic-html
    image: imsuraj/nodejs-dynamic-html:latest

