version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  ml-text-generation:
    lang: python3-http-debian
    handler: ./ml-text-generation
    image: imsuraj/ml-text-generation:latest

