version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  matmul:
    lang: python3-http-debian
    handler: ./matmul
    image: imsuraj/matmul:latest
    labels:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "5"
