version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  nodejs-auto-complete:
    lang: node20
    handler: ./nodejs-auto-complete
    image: imsuraj/nodejs-auto-complete:latest

