version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  markdown:
    lang: python3-http-debian
    handler: ./markdown
    image: imsuraj/markdown:latest
    labels:
      com.openfaas.scale.min: "2"
      com.openfaas.scale.max: "5"
