provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  memory-slammer:
    lang: python3-http
    handler: ./memory-slammer
    image: imsuraj/memory-slammer:latest
    resources:
      requests:
        memory: 28Gi
      limits:
        memory: 28Gi
