provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  memory-slammer:
    lang: python3-http-debian
    handler: ./memory-slammer
    image:  imsuraj/memory-slammer:latest
    limits:
      memory: 26Gi
    requests:
      memory: 26Gi
    environment:
      write_debug: true