version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  video-processing:
    lang: python3-http-debian
    handler: ./video-processing
    image: imsuraj/video-processing:latest
